services:
- type: web
  name: pryMongoEsp32
  runtime: python
  repo: https://github.com/ElPitirijas645/Prueba1000.git
  plan: free
  envVars:
  - key: MONGO_URI
    value: mongodb+srv://crismartinez645:123456789012@elpitirijas645.e2xixee.mongodb.net/?retryWrites=true&w=majority&appName=ElPitirijas645
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
version: "1"
